const { FF1, DIGITS: FF1_DIGITS, ALPHANUMERIC: FF1_ALPHA } = require("./ff1");
const { FF3, DIGITS: FF3_DIGITS, ALPHANUMERIC: FF3_ALPHA } = require("./ff3");

const DIGITS = FF1_DIGITS;
const ALPHANUMERIC = FF1_ALPHA;

module.exports = { FF1, FF3, DIGITS, ALPHANUMERIC };
